spring:
  application:
    name: SchedulerJob

  datasource:
    url: jdbc:mysql://localhost:3306/spring-boot-schedulerjob?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # Options: none, update, create, create-drop
    show-sql: true # Set to false in production for security and performance
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect # Or appropriate dialect for your MySQL version

  mail:
    host: smtp.gmail.com
    port: 587
    username: 'ksaikrishna2244@gmail.com'
    password: 'nucq uspw qdwd cyxo'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true